### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by fanzypantz** [amicaldo/strapi-google-maps#5]
Hi, like CKEditor5 plugin for strapi(now solved), we are seeing the issue of not being able to run the yarn install due to the upper limit on the engine in package.json. 

This works fine in node 20 right? Can we get a bump of the node version?

**Comment by roodekk** [comment]
Thanks for the suggestion, you can now update to version 1.1.4 which supports Node v20.
https://github.com/amicaldo/strapi-google-maps/commit/07c788516c1964b8a9cea951f7de21f010ebae7a
