### ISSUE TITLE
Support for Node 20

### ISSUE THREAD

**Issue by chriscborg** [amicaldo/strapi-google-maps#9]
# Description
The latest version of Strapi recommends using Node 20 for a major improvement in performance with Node 18 being the minimum. `strapi-google-maps` support until Node 18 and needs to be bumped to support Node 20. 

When attempting to build Strapi with Node 20, I'm getting the error saying `error @amicaldo/strapi-google-maps@1.1.4: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <20.x.x". Got "20.13.1"`

**Comment by roest01** [comment]
Hey @chriscborg,
We are on it =)
